owner: usevital
repo: uptime

sites:
  - name: Vital Website
    url: https://usevital.github.io/
  - name: NotEssential Website
    url: https://notessential.blurry.gay/
  - name: Ward Website
    url: https://ward.worldwidepixel.ca/

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/vital128.png
  name: Vital Projects Uptime
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
