owner: usevital
repo: uptime

sites:
  - name: Vital Website
    url: https://usevital.github.io/
    icon: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/vital.png
  - name: NotEssential Website
    url: https://notessential.blurry.gay/
    icon: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/ne.png
  - name: Ward Website
    url: https://ward.worldwidepixel.ca/
    icon: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/ward.png

assignees:
  - Nitrrine
  - KTrain5169
  - worldwidepixel
  - blryface

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/vital.png
  favicon: https://raw.githubusercontent.com/usevital/uptime/refs/heads/master/assets/vital.png
  name: Vital Projects Uptime
  introTitle: "Status page for Vital-related projects."
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
